In [0]:
import numpy as np
a = np.array([1,-1,0,2])
np.exp(a)

array([2.71828183, 0.36787944, 1.        , 7.3890561 ])

In [0]:
b = np.array([2,4,3,1])
np.sum(b)

10

In [0]:
np.sum(np.exp(a))

11.475217368561138

In [0]:
def softmax(a):
  return np.exp(a) / np.sum(np.exp(a))

In [0]:
softmax([4,5,2,1])

array([0.25618664, 0.69638749, 0.03467109, 0.01275478])

In [0]:
np.argmax([4,5,2,1])

1

In [0]:
b

array([2, 4, 3, 1])

In [0]:
b / np.sum(b)

array([0.2, 0.4, 0.3, 0.1])

In [5]:
import numpy as np

data = np.array(((20,30), (60,75), (80,30), (90,70), (95,90), (40,60), (80,90), (30,40), (25,55), (35,25), (80,45), (50,10), (25,80)))
y = np.array((0,1,0,1,1,1,1,0,0,0,1,0,1))
w = np.array((0.1, 0.3, -20))

def linclass(w,a):
  if w[0] * a[0] + w[1] * a[1] + w[2] >= 0:
    return 1
  else:
    return 0

wrong = 0
for x, truth in zip(data,y):
  # print('x = ', x, ', truth = ', truth)
  prediction = linclass(w,x)
  wrong += np.abs(prediction - truth)
  
print('wrong = ', wrong)

wrong =  0


In [11]:
import numpy as np

data = np.array(((20,30), (60,75), (80,30), (90,70), (95,90), (40,60), (80,90), (30,40), (25,55), (35,25), (80,45), (50,10), (25,80)))
y = np.array((0,1,0,1,1,1,1,0,0,0,1,0,1))
w = np.array((0.1, 0.3, -20))

def linclass(weight, input_x):
  if np.matmul(weight, input_x) >= 0:
    return 1
  else:
    return 0

wrong = 0
for x, truth in zip(data,y):
  x_withb = np.concatenate((x,np.ones((1))))
  # print('x_withb = ', x_withb, ', truth = ', truth)
  prediction = linclass(w, x_withb)
  wrong += np.abs(prediction - truth)
  
print('wrong = ', wrong)

wrong =  0
