In [1]:
import numpy as np

In [2]:
v = np.array((4,3,2))
u = np.array((1,5,2))

In [3]:
# elementwise product (Hadamard product)
[e1 * e2 for e1, e2 in zip(v, u)]

[4, 15, 4]

In [4]:
# compute inner product
np.sum(np.array([e1 * e2 for e1, e2 in zip(v, u)]))

23

In [5]:
A = np.random.random((5,3))
B = np.random.random((3,4))

In [6]:
A

array([[0.62350009, 0.00119296, 0.35265267],
       [0.00436978, 0.61236331, 0.73766116],
       [0.40433978, 0.96692252, 0.47121614],
       [0.00561098, 0.20562243, 0.909549  ],
       [0.07622477, 0.40129248, 0.05597344]])

In [7]:
B

array([[0.52531052, 0.79539217, 0.14797152, 0.89700386],
       [0.34370511, 0.0042822 , 0.20851809, 0.11215842],
       [0.2256828 , 0.4469294 , 0.35510653, 0.00465795]])

In [8]:
np.matmul(A,B)

array([[0.40752883, 0.65354305, 0.21773828, 0.56105843],
       [0.37924533, 0.33578041, 0.39028373, 0.0760374 ],
       [0.65108553, 0.5363496 , 0.42878354, 0.47333775],
       [0.27889056, 0.41184764, 0.36669305, 0.03233199],
       [0.19060019, 0.08736317, 0.11483237, 0.11364296]])

In [9]:
# matrix multiplication using loops
def my_matmul(X, Y):
    return np.array([[np.matmul(x, y) for y in Y.transpose()] for x in X])
    
my_matmul(A,B)

array([[0.40752883, 0.65354305, 0.21773828, 0.56105843],
       [0.37924533, 0.33578041, 0.39028373, 0.0760374 ],
       [0.65108553, 0.5363496 , 0.42878354, 0.47333775],
       [0.27889056, 0.41184764, 0.36669305, 0.03233199],
       [0.19060019, 0.08736317, 0.11483237, 0.11364296]])